apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: topolvm-webhook-ca
  namespace: topolvm-system
  labels:
    helm.sh/chart: topolvm-7.0.0
    app.kubernetes.io/name: topolvm
    app.kubernetes.io/instance: topolvm
    app.kubernetes.io/version: "0.13.0"
    app.kubernetes.io/managed-by: Helm
spec:
  ca:
    secretName: topolvm-webhook-ca
