kind: Deployment
apiVersion: apps/v1
metadata:
  name: thanos-querier-proxy
  namespace: openshift-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: thanos-querier-proxy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: thanos-querier-proxy
    spec:
      serviceAccountName: thanos-querier
      containers:
        - resources:
            requests:
              cpu: 1m
              memory: 10Mi
          name: thanos-proxy
          ports:
            - name: thanos-proxy
              containerPort: 9091
              protocol: TCP
          volumeMounts:
            - name: secret-thanos-querier-tls
              mountPath: /etc/tls/private
            - name: secret-thanos-querier-oauth-cookie
              mountPath: /etc/proxy/secrets
            - name: thanos-querier-trusted-ca-bundle
              readOnly: true
              mountPath: /etc/pki/ca-trust/extracted/pem/
          image: >-
            quay.io/openshift/okd-content:4.10.0-0.okd-2022-05-07-021833-oauth-proxy
          args:
            - '-provider=openshift'
            - '-https-address=:9091'
            - '-http-address='
            - '-email-domain=*'
            - '-upstream=http://vmsingle-metrics:8429'
            - '-openshift-service-account=thanos-querier'
            - '-openshift-sar={"resource": "namespaces", "verb": "get"}'
            - >-
              -openshift-delegate-urls={"/": {"resource": "namespaces", "verb":
              "get"}}
            - '-tls-cert=/etc/tls/private/tls.crt'
            - '-tls-key=/etc/tls/private/tls.key'
            - >-
              -client-secret-file=/var/run/secrets/kubernetes.io/serviceaccount/token
            - '-cookie-secret-file=/etc/proxy/secrets/session_secret'
            - '-openshift-ca=/etc/pki/tls/cert.pem'
            - '-openshift-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt'
            - '-bypass-auth-for=^/-/(healthy|ready)$'
      volumes:
      - name: secret-thanos-querier-tls
        secret:
          secretName: thanos-querier-tls
          defaultMode: 420
      - name: secret-thanos-querier-oauth-cookie
        secret:
          secretName: thanos-querier-oauth-cookie
          defaultMode: 420
      - name: thanos-querier-trusted-ca-bundle
        configMap:
          name: thanos-querier-trusted-ca-bundle
          items:
            - key: ca-bundle.crt
              path: tls-ca-bundle.pem
          defaultMode: 420
          optional: true
