kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: thanos-querier-oauth-proxy
subjects:
  - kind: ServiceAccount
    name: thanos-querier
    namespace: openshift-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: oauth-proxy
