apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: topolvm-controller
  namespace: topolvm-system
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/name: topolvm
      app.kubernetes.io/instance: topolvm
