apiVersion: v1
kind: Service
metadata:
  name: topolvm-controller
  namespace: topolvm-system
  labels:
    helm.sh/chart: topolvm-7.0.0
    app.kubernetes.io/name: topolvm
    app.kubernetes.io/instance: topolvm
    app.kubernetes.io/version: "0.13.0"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    app.kubernetes.io/component: controller
    
    app.kubernetes.io/name: topolvm
    app.kubernetes.io/instance: topolvm
  ports:
    - name: webhook
      port: 443
      protocol: TCP
      targetPort: webhook
