apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: ethernet
spec:
  desiredState:
    interfaces:
    - name: enp0s31f6
      type: ethernet
      state: up
      ipv4:
        dhcp: true
        enabled: true
