kind: Service
apiVersion: v1
metadata:
  name: ingress
  namespace: ingress-nginx
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ingress-nginx
