kind: Deployment
apiVersion: apps/v1
metadata:
  name: filesync
  namespace: filesync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filesync
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: filesync
    spec:
      restartPolicy: Always
      securityContext:
        runAsUser: 0
      containers:
        - name: filesync
          image: >-
            docker.io/machines/filestash:latest
          ports:
            - containerPort: 8334
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /data
              subPath: shared
            - name: data
              mountPath: /app/data/state/
              subPath: filestash-settings
        - name: syncthing
          env:
            - name: PUID
              value: '0'
            - name: GUID
              value: '0'
          ports:
            - containerPort: 21027
              protocol: UDP
            - containerPort: 22000
              protocol: TCP
            - containerPort: 8384
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /config
              subPath: syncthing-config
            - name: data
              mountPath: /data
              subPath: shared
          image: >-
            ghcr.io/linuxserver/syncthing:1.20.3
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: filesync
      dnsPolicy: ClusterFirst
