kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: filesync
  namespace: filesync
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
