apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: topolvm
  annotations:
    storageclass.kubernetes.io/is-default-class: 'true'
value: 1e+06
globalDefault: false
description: "Pods using TopoLVM volumes should use this class."
