apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: topolvm-lvmd-0
  namespace: topolvm-system
  labels:
    idx: "0"
    helm.sh/chart: topolvm-7.0.0
    app.kubernetes.io/name: topolvm
    app.kubernetes.io/instance: topolvm
    app.kubernetes.io/version: "0.13.0"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      idx: "0"
      app.kubernetes.io/component: lvmd
      
      app.kubernetes.io/name: topolvm
      app.kubernetes.io/instance: topolvm
  template:
    metadata:
      labels:
        idx: "0"
        app.kubernetes.io/component: lvmd
        
        app.kubernetes.io/name: topolvm
        app.kubernetes.io/instance: topolvm
      annotations:
        checksum/config: 865a45b5219d9a81acb764543a491f9e9457205aa8f37cb4326bf0baf572c423
        prometheus.io/port: metrics
    spec:
      serviceAccountName: topolvm-lvmd
      hostPID: true
      containers:
        - name: lvmd
          image: "ghcr.io/topolvm/topolvm-with-sidecar:0.13.0"
          securityContext:
            privileged: true
          command:
            - /lvmd
            - --container
          volumeMounts:
            - name: config
              mountPath: /etc/topolvm
            - name: lvmd-socket-dir
              mountPath: /run/topolvm
      volumes:
        - name: config
          configMap:
            name: topolvm-lvmd-0
        - name: lvmd-socket-dir
          hostPath:
            path: /run/topolvm
            type: DirectoryOrCreate
