apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: openshift-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      name: alertmanager
      labels:
        app: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: quay.io/prometheus/alertmanager:v0.24.0
        ports:
        - name: alertmanager
          containerPort: 9093
        volumeMounts:
        - name: alertmanager
          mountPath: /alertmanager
      volumes:
      - name: alertmanager
        emptyDir: {}
