apiVersion: v1
kind: Service
metadata:
  name: thanos-querier
  namespace: openshift-monitoring
spec:
  ports:
  - port: 9091
    protocol: TCP
    targetPort: 9091
    name: web
  - port: 9092
    protocol: TCP
    targetPort: 9091
    name: metrics
  selector:
    app.kubernetes.io/name: thanos-querier-proxy
  type: ClusterIP
