apiVersion: v1
kind: Service
metadata:
  name: adguard
  namespace: adguard
spec:
  ports:
  - port: 3000
    name: http
    protocol: TCP
    targetPort: 3000
  selector:
    app: adguard
  type: ClusterIP
