apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: topolvm-node
  namespace: topolvm-system
  labels:
    helm.sh/chart: topolvm-7.0.0
    app.kubernetes.io/name: topolvm
    app.kubernetes.io/instance: topolvm
    app.kubernetes.io/version: "0.13.0"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: node
      
      app.kubernetes.io/name: topolvm
      app.kubernetes.io/instance: topolvm
  template:
    metadata:
      labels:
        app.kubernetes.io/component: node
        
        app.kubernetes.io/name: topolvm
        app.kubernetes.io/instance: topolvm
      annotations: 
        prometheus.io/port: metrics
    spec:
      serviceAccountName: topolvm-node
      containers:
        - name: topolvm-node
          image: "ghcr.io/topolvm/topolvm-with-sidecar:0.13.0"
          securityContext: 
            privileged: true
          command:
            - /topolvm-node
            - --csi-socket=/var/lib/kubelet/plugins/topolvm.cybozu.com/node/csi-topolvm.sock
            - --lvmd-socket=/run/topolvm/lvmd.sock
          ports:
            - name: healthz
              containerPort: 9808
              protocol: TCP
            - name: metrics
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
            failureThreshold: 3
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 60
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: node-plugin-dir
              mountPath: /var/lib/kubelet/plugins/topolvm.cybozu.com/node/
            - name: lvmd-socket-dir
              mountPath: /run/topolvm
            - name: pod-volumes-dir
              mountPath: /var/lib/kubelet/pods
              mountPropagation: "Bidirectional"
            - name: csi-plugin-dir
              mountPath: /var/lib/kubelet/plugins/kubernetes.io/csi
              mountPropagation: "Bidirectional"

        - name: csi-registrar
          image: "ghcr.io/topolvm/topolvm-with-sidecar:0.13.0"
          command:
            - /csi-node-driver-registrar
            - --csi-address=/var/lib/kubelet/plugins/topolvm.cybozu.com/node/csi-topolvm.sock
            - --kubelet-registration-path=/var/lib/kubelet/plugins/topolvm.cybozu.com/node/csi-topolvm.sock
          livenessProbe:
            exec:
              command:
              - /csi-node-driver-registrar
              - --kubelet-registration-path=/var/lib/kubelet/plugins/topolvm.cybozu.com/node/csi-topolvm.sock
              - --mode=kubelet-registration-probe
            initialDelaySeconds: 3
          lifecycle:
            preStop:
              exec:
                command:
                - /bin/sh
                - -c
                - rm -rf /registration/topolvm.cybozu.com /registration/topolvm.cybozu.com-reg.sock
          volumeMounts:
            - name: node-plugin-dir
              mountPath: /var/lib/kubelet/plugins/topolvm.cybozu.com/node/
            - name: registration-dir
              mountPath: /registration

        - name: liveness-probe
          image: "ghcr.io/topolvm/topolvm-with-sidecar:0.13.0"
          command:
            - /livenessprobe
            - --csi-address=/var/lib/kubelet/plugins/topolvm.cybozu.com/node/csi-topolvm.sock
          volumeMounts:
            - name: node-plugin-dir
              mountPath: /var/lib/kubelet/plugins/topolvm.cybozu.com/node/

      volumes:
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry/
            type: Directory
        - name: node-plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/topolvm.cybozu.com/node
            type: DirectoryOrCreate
        - name: csi-plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/kubernetes.io/csi
            type: DirectoryOrCreate
        - name: pod-volumes-dir
          hostPath:
            path: /var/lib/kubelet/pods/
            type: DirectoryOrCreate
        - name: lvmd-socket-dir
          hostPath:
            path: /run/topolvm
            type: Directory
