apiVersion: v1
kind: ConfigMap
metadata:
  name: topolvm-scheduler-options
  namespace: topolvm-system
  labels:
    helm.sh/chart: topolvm-7.0.0
    app.kubernetes.io/name: topolvm
    app.kubernetes.io/instance: topolvm
    app.kubernetes.io/version: "0.13.0"
    app.kubernetes.io/managed-by: Helm
data:
  scheduler-options.yaml: |
    listen: "localhost:9251"
    default-divisor: 1
