apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: topolvm-scheduler
  namespace: topolvm-system
  labels:
    helm.sh/chart: topolvm-7.0.0
    app.kubernetes.io/name: topolvm
    app.kubernetes.io/instance: topolvm
    app.kubernetes.io/version: "0.13.0"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: scheduler
      
      app.kubernetes.io/name: topolvm
      app.kubernetes.io/instance: topolvm
  template:
    metadata:
      annotations:
        checksum/config: 4c92ce91b40e7df5f8a21b0a25469188aee183bcd52fad9d258c2ef8b7bf8e79
      labels:
        app.kubernetes.io/component: scheduler
        
        app.kubernetes.io/name: topolvm
        app.kubernetes.io/instance: topolvm
    spec:
      securityContext: 
        runAsGroup: 10000
        runAsUser: 10000
      serviceAccountName: topolvm-scheduler
      containers:
        - name: topolvm-scheduler
          image: "ghcr.io/topolvm/topolvm-with-sidecar:0.13.0"
          command:
            - /topolvm-scheduler
            - --config=/etc/topolvm/scheduler-options.yaml
          livenessProbe:
            httpGet:
              host: localhost
              port: 9251
              path: /status
          readinessProbe:
            httpGet:
              host: localhost
              port: 9251
              path: /status
          volumeMounts:
            - mountPath: /etc/topolvm
              name: topolvm-scheduler-options
      hostNetwork: true
      volumes:
        - name: topolvm-scheduler-options
          configMap:
            name: topolvm-scheduler-options
      affinity: 
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
      tolerations: 
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
