apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: topolvm
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: infra
  source:
    path: apps/infra/topolvm
    repoURL: 'https://github.com/vrutkovs/k3router'
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
