apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: infra
  source:
    path: apps/infra/cert-manager
    repoURL: 'https://github.com/vrutkovs/k3router'
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
