apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: user
  source:
    path: apps/user/home-assistant
    repoURL: 'https://github.com/vrutkovs/k3router'
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
